### ISSUE TITLE
Unable to use Error as a base type

### ISSUE THREAD

**Issue by smfields** [modabas/Orleans.Serialization.FluentResults#2]
I've been trying to get FluentResults to work with Orleans, and I'm super grateful I was able to find your converters. However, I'm still unable to use the Error type from FluentResults as a base type for my own custom errors.

I'm getting an error inside the `ErrorSurrogateConverter` when it calls `Populate`. The error is caused by the `Reasons` field on the supplied Error being null, which happens because when Orleans creates the type to populate it does not use the constructor, thereby avoiding the initialization of the `Reasons` and `Metadata` properties on the Error.

Have you been able to successfully use your converters to convert custom error classes that extend Error?

**Comment by modabas** [comment]
I have used custom errors only with message, without any other properties (i.e. reasons, metadata)

```
[GenerateSerializer]
internal class QueryReturnedOldDataError : Error
{
    public QueryReturnedOldDataError()
        : base("Query response contains data older than persisted one.")
    {
    }
}
```


```
return Result.Fail(new QueryReturnedOldDataError());
```
